# Generated by Django 4.0.5 on 2022-06-21 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_room_options_room_participants'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-created', '-updated']},
        ),
    ]
