apiVersion : v1
kind : Service
metadata :
  name : mywebapp-service # This is name for service irrespective of its deployment
spec :
  selector : 
    app : webapp-sql
    tier : frontend
  ports :
  - port : 80
  type : NodePort    