apiVersion : apps/v1
kind :  Deployment
metadata :
  name : nginx-deployment
  labels : 
    app : nginx
spec : 
  replicas : 2   
    # This will create two pods for container. If you delete a pod kubernetes will self-heal and create a pod as you specified for 2 replicas
  selector : 
    matchLabels : 
      app : nginx
  template : 
    metadata :
      labels : 
        app : nginx
    spec : 
      containers :
      - name : nginx
        image : nginx:1.16
        ports :
        - containerPort : 80   
