apiVersion : v1
kind : Pod
metadata : 
  name : nginx-pod
  labels :
    env : localenv
    identifier : nginx-local-pod
    type : pod-create
spec :
  containers :
  - name : nginx-container
    image : nginx
    ports :
      - containerPort : 80  
